### ISSUE TITLE
Probation period

### ISSUE THREAD

**Issue by mike-anthony** [mike-anthony/ProcessJumplinks#3]
SteveB [mentioned](https://processwire.com/talk/topic/8697-alpha-processadvancedredirects/#entry84097) that people may have second thoughts regarding their redirects.

Should we implement a probation period? During such period, a redirect would send a 302 status code. After the period, it would send a 301, and become uneditable/undeletable.

:speech_balloon:

**Comment by mike-anthony** [comment]
Not enough interest shown. Closing for now.

**Comment by mikerockett** [comment]
Update: Jumplinks 2 will use a type setter, leaving the decision up to the user.
