### ISSUE TITLE
Notice: Trying to get property of non-object

### ISSUE THREAD

**Issue by motionVector** [mike-anthony/ProcessJumplinks#7]
Getting this error with the latest update to 1.2.0: `Notice: Trying to get property of non-object in /var/www/public/site/modules/ProcessJumplinks/ProcessJumplinks.module on line 259`
I tried it with Processwire version 2.5.26 and 2.5.27.
But redirecting also didn’t work before updating to 1.2.0. I checked what happens with debug mode on and it said the pattern matched, but when I turned debug mode off again I only got the 404 error without redirect to the right uri.
Your module looks great. I hope you could help me to get it to work. For my next redesign of a website it would really help me a lot.

**Comment by mike-anthony** [comment]
Thanks for reporting that - didn't notice it until I uninstalled ProcessRedirects.

Have synced a hotfix. Working on my side now, but please confirm on yours before I close.

Thanks. :+1:

**Comment by motionVector** [comment]
Thanks, the error is gone :)

**Comment by mike-anthony** [comment]
:+1:
